// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "noums@hacker.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/shoes": {
            "get": {
                "description": "Obtenir la liste complète des chaussures disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shoes"
                ],
                "summary": "Récupère toutes les chaussures",
                "responses": {
                    "200": {
                        "description": "Liste des chaussures",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Shoe"
                            }
                        }
                    },
                    "500": {
                        "description": "Erreur serveur",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Shoe": {
            "description": "Shoe product information",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-06-01T15:04:05Z"
                },
                "description": {
                    "description": "Description du produit\nExemple: Classic sneaker with air cushioning",
                    "type": "string",
                    "example": "Classic sneaker with air cushioning"
                },
                "id": {
                    "type": "integer"
                },
                "images": {
                    "description": "Images associées à la chaussure",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ShoeImage"
                    }
                },
                "marque": {
                    "description": "Marque de la chaussure\nExemple: Nike",
                    "type": "string",
                    "example": "Nike"
                },
                "name": {
                    "description": "Nom du modèle\nExemple: Air Max 90",
                    "type": "string",
                    "example": "Air Max 90"
                },
                "price": {
                    "description": "Prix\nExemple: 120.99",
                    "type": "number",
                    "example": 120.99
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-06-01T15:04:05Z"
                }
            }
        },
        "models.ShoeImage": {
            "description": "Image associée à un produit chaussure",
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-06-01T15:04:05Z"
                },
                "id": {
                    "type": "integer"
                },
                "shoe_id": {
                    "description": "ID de la chaussure associée",
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-06-01T15:04:05Z"
                },
                "url": {
                    "description": "URL de l'image",
                    "type": "string",
                    "example": "https://example.com/shoe.jpg"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "SUN CO. API",
	Description:      "API pour l'application SUN CO.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
